#install.packages("tidyverse")
#install.packages(c("tidyverse", "ggplot2", "ggdist", "ggstatsplot", "cowplot", "dplyr", 'PupillometryR', 'Rlab'))
#/home/ketrong/R/x86_64-pc-linux-gnu-library/4.4/
#library(tidyverse, lib.loc = "/R/x86_64-pc-linux-gnu-library/4.4")
#library(agridat, lib.loc = "/R/x86_64-pc-linux-gnu-library/4.4")
#library(ggplot2, lib.loc = "/R/x86_64-pc-linux-gnu-library/4.4")
#library(ghibli, lib.loc = "/R/x86_64-pc-linux-gnu-library/4.4")
#library(ggstatsplot, lib.loc = "/R/x86_64-pc-linux-gnu-library/4.4")
#library(ISLR, lib.loc = "/R/x86_64-pc-linux-gnu-library/4.4")
#library(tidyverse, lib.loc = "/R/x86_64-pc-linux-gnu-library/4.4")

library(ggplot2)
#library(ghibli)
library(ggdist)
library(tidyverse)
#install.packages("ggstatsplot")
library(ggstatsplot)
#install.packages("ISLR")
#library(ISLR)
library(ggplot2)
library(cowplot)
library(dplyr)
library(PupillometryR)
library(Rlab)

spinefirstresults <- read.csv("/Users/gabrielketron/class_kw/spine_first.csv")
expertandcomplexresults <- read.csv("/Users/gabrielketron/class_kw/spine.csv")
simplefirstandsimpleresults <- read.csv("/Users/gabrielketron/class_kw/spine_simple.csv")
nonsimple<- read.csv("/Users/gabrielketron/class_kw/spine_nonsimple_new.csv")

print('Expert')
print(mean(expertandcomplexresults$Exp2impute_f1))
print('Mixed')
print(mean(expertandcomplexresults$Exp3impute_f1))
print('NonSimple')
print(mean(nonsimple$Exp3impute_f1))
print('Simple')
print(mean(simplefirstandsimpleresults$Exp3impute_f1))
